name: Oily Concepts Solutions
favicon: null
layout_spectrum: 0.933584
typography_spectrum: 0.3621554
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0F150E'
    - '#99BD91'
    - '#415C39'
    - '#C6BD17'
    - '#C8C564'
  brandStrength: 0.6071429
  lightness: 0.75
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
