layout_spectrum: 0.933584
color:
  saturation: 0.508772
  lightness: 0.5012531
  brandStrength: 0.6071429
  brandColors:
    - '#0F150E'
    - '#99BD91'
    - '#415C39'
    - '#C6BD17'
    - '#C8C564'
  rhythmicContrast: 0.7825814
typography_spectrum: 0.3621554
name: Oily Concepts Solutions
